/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TradersRouteImport } from './routes/traders'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as QuestsRouteImport } from './routes/quests'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as MapsRouteImport } from './routes/maps'
import { Route as ItemsRouteImport } from './routes/items'
import { Route as HideoutRouteImport } from './routes/hideout'
import { Route as AttributionsRouteImport } from './routes/attributions'
import { Route as ArcsRouteImport } from './routes/arcs'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TradersTraderIdRouteImport } from './routes/traders_.$traderId'
import { Route as ToolsDiscordBotRouteImport } from './routes/tools.discord-bot'
import { Route as QuestsQuestIdRouteImport } from './routes/quests_.$questId'
import { Route as MapsMapIdRouteImport } from './routes/maps_.$mapId'
import { Route as ItemsRecyclesRouteImport } from './routes/items_.recycles'
import { Route as ItemsItemIdRouteImport } from './routes/items_.$itemId'
import { Route as HideoutCraftsRouteImport } from './routes/hideout_.crafts'
import { Route as HideoutWorkbenchIdRouteImport } from './routes/hideout_.$workbenchId'
import { Route as ArcsArcIdRouteImport } from './routes/arcs_.$arcId'

const TradersRoute = TradersRouteImport.update({
  id: '/traders',
  path: '/traders',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestsRoute = QuestsRouteImport.update({
  id: '/quests',
  path: '/quests',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const MapsRoute = MapsRouteImport.update({
  id: '/maps',
  path: '/maps',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemsRoute = ItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => rootRouteImport,
} as any)
const HideoutRoute = HideoutRouteImport.update({
  id: '/hideout',
  path: '/hideout',
  getParentRoute: () => rootRouteImport,
} as any)
const AttributionsRoute = AttributionsRouteImport.update({
  id: '/attributions',
  path: '/attributions',
  getParentRoute: () => rootRouteImport,
} as any)
const ArcsRoute = ArcsRouteImport.update({
  id: '/arcs',
  path: '/arcs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TradersTraderIdRoute = TradersTraderIdRouteImport.update({
  id: '/traders_/$traderId',
  path: '/traders/$traderId',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsDiscordBotRoute = ToolsDiscordBotRouteImport.update({
  id: '/tools/discord-bot',
  path: '/tools/discord-bot',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestsQuestIdRoute = QuestsQuestIdRouteImport.update({
  id: '/quests_/$questId',
  path: '/quests/$questId',
  getParentRoute: () => rootRouteImport,
} as any)
const MapsMapIdRoute = MapsMapIdRouteImport.update({
  id: '/maps_/$mapId',
  path: '/maps/$mapId',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemsRecyclesRoute = ItemsRecyclesRouteImport.update({
  id: '/items_/recycles',
  path: '/items/recycles',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemsItemIdRoute = ItemsItemIdRouteImport.update({
  id: '/items_/$itemId',
  path: '/items/$itemId',
  getParentRoute: () => rootRouteImport,
} as any)
const HideoutCraftsRoute = HideoutCraftsRouteImport.update({
  id: '/hideout_/crafts',
  path: '/hideout/crafts',
  getParentRoute: () => rootRouteImport,
} as any)
const HideoutWorkbenchIdRoute = HideoutWorkbenchIdRouteImport.update({
  id: '/hideout_/$workbenchId',
  path: '/hideout/$workbenchId',
  getParentRoute: () => rootRouteImport,
} as any)
const ArcsArcIdRoute = ArcsArcIdRouteImport.update({
  id: '/arcs_/$arcId',
  path: '/arcs/$arcId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/arcs': typeof ArcsRoute
  '/attributions': typeof AttributionsRoute
  '/hideout': typeof HideoutRoute
  '/items': typeof ItemsRoute
  '/maps': typeof MapsRoute
  '/privacy': typeof PrivacyRoute
  '/quests': typeof QuestsRoute
  '/terms': typeof TermsRoute
  '/traders': typeof TradersRoute
  '/arcs/$arcId': typeof ArcsArcIdRoute
  '/hideout/$workbenchId': typeof HideoutWorkbenchIdRoute
  '/hideout/crafts': typeof HideoutCraftsRoute
  '/items/$itemId': typeof ItemsItemIdRoute
  '/items/recycles': typeof ItemsRecyclesRoute
  '/maps/$mapId': typeof MapsMapIdRoute
  '/quests/$questId': typeof QuestsQuestIdRoute
  '/tools/discord-bot': typeof ToolsDiscordBotRoute
  '/traders/$traderId': typeof TradersTraderIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/arcs': typeof ArcsRoute
  '/attributions': typeof AttributionsRoute
  '/hideout': typeof HideoutRoute
  '/items': typeof ItemsRoute
  '/maps': typeof MapsRoute
  '/privacy': typeof PrivacyRoute
  '/quests': typeof QuestsRoute
  '/terms': typeof TermsRoute
  '/traders': typeof TradersRoute
  '/arcs/$arcId': typeof ArcsArcIdRoute
  '/hideout/$workbenchId': typeof HideoutWorkbenchIdRoute
  '/hideout/crafts': typeof HideoutCraftsRoute
  '/items/$itemId': typeof ItemsItemIdRoute
  '/items/recycles': typeof ItemsRecyclesRoute
  '/maps/$mapId': typeof MapsMapIdRoute
  '/quests/$questId': typeof QuestsQuestIdRoute
  '/tools/discord-bot': typeof ToolsDiscordBotRoute
  '/traders/$traderId': typeof TradersTraderIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/arcs': typeof ArcsRoute
  '/attributions': typeof AttributionsRoute
  '/hideout': typeof HideoutRoute
  '/items': typeof ItemsRoute
  '/maps': typeof MapsRoute
  '/privacy': typeof PrivacyRoute
  '/quests': typeof QuestsRoute
  '/terms': typeof TermsRoute
  '/traders': typeof TradersRoute
  '/arcs_/$arcId': typeof ArcsArcIdRoute
  '/hideout_/$workbenchId': typeof HideoutWorkbenchIdRoute
  '/hideout_/crafts': typeof HideoutCraftsRoute
  '/items_/$itemId': typeof ItemsItemIdRoute
  '/items_/recycles': typeof ItemsRecyclesRoute
  '/maps_/$mapId': typeof MapsMapIdRoute
  '/quests_/$questId': typeof QuestsQuestIdRoute
  '/tools/discord-bot': typeof ToolsDiscordBotRoute
  '/traders_/$traderId': typeof TradersTraderIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/arcs'
    | '/attributions'
    | '/hideout'
    | '/items'
    | '/maps'
    | '/privacy'
    | '/quests'
    | '/terms'
    | '/traders'
    | '/arcs/$arcId'
    | '/hideout/$workbenchId'
    | '/hideout/crafts'
    | '/items/$itemId'
    | '/items/recycles'
    | '/maps/$mapId'
    | '/quests/$questId'
    | '/tools/discord-bot'
    | '/traders/$traderId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/arcs'
    | '/attributions'
    | '/hideout'
    | '/items'
    | '/maps'
    | '/privacy'
    | '/quests'
    | '/terms'
    | '/traders'
    | '/arcs/$arcId'
    | '/hideout/$workbenchId'
    | '/hideout/crafts'
    | '/items/$itemId'
    | '/items/recycles'
    | '/maps/$mapId'
    | '/quests/$questId'
    | '/tools/discord-bot'
    | '/traders/$traderId'
  id:
    | '__root__'
    | '/'
    | '/arcs'
    | '/attributions'
    | '/hideout'
    | '/items'
    | '/maps'
    | '/privacy'
    | '/quests'
    | '/terms'
    | '/traders'
    | '/arcs_/$arcId'
    | '/hideout_/$workbenchId'
    | '/hideout_/crafts'
    | '/items_/$itemId'
    | '/items_/recycles'
    | '/maps_/$mapId'
    | '/quests_/$questId'
    | '/tools/discord-bot'
    | '/traders_/$traderId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArcsRoute: typeof ArcsRoute
  AttributionsRoute: typeof AttributionsRoute
  HideoutRoute: typeof HideoutRoute
  ItemsRoute: typeof ItemsRoute
  MapsRoute: typeof MapsRoute
  PrivacyRoute: typeof PrivacyRoute
  QuestsRoute: typeof QuestsRoute
  TermsRoute: typeof TermsRoute
  TradersRoute: typeof TradersRoute
  ArcsArcIdRoute: typeof ArcsArcIdRoute
  HideoutWorkbenchIdRoute: typeof HideoutWorkbenchIdRoute
  HideoutCraftsRoute: typeof HideoutCraftsRoute
  ItemsItemIdRoute: typeof ItemsItemIdRoute
  ItemsRecyclesRoute: typeof ItemsRecyclesRoute
  MapsMapIdRoute: typeof MapsMapIdRoute
  QuestsQuestIdRoute: typeof QuestsQuestIdRoute
  ToolsDiscordBotRoute: typeof ToolsDiscordBotRoute
  TradersTraderIdRoute: typeof TradersTraderIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/traders': {
      id: '/traders'
      path: '/traders'
      fullPath: '/traders'
      preLoaderRoute: typeof TradersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quests': {
      id: '/quests'
      path: '/quests'
      fullPath: '/quests'
      preLoaderRoute: typeof QuestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maps': {
      id: '/maps'
      path: '/maps'
      fullPath: '/maps'
      preLoaderRoute: typeof MapsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/items': {
      id: '/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof ItemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hideout': {
      id: '/hideout'
      path: '/hideout'
      fullPath: '/hideout'
      preLoaderRoute: typeof HideoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attributions': {
      id: '/attributions'
      path: '/attributions'
      fullPath: '/attributions'
      preLoaderRoute: typeof AttributionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arcs': {
      id: '/arcs'
      path: '/arcs'
      fullPath: '/arcs'
      preLoaderRoute: typeof ArcsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/traders_/$traderId': {
      id: '/traders_/$traderId'
      path: '/traders/$traderId'
      fullPath: '/traders/$traderId'
      preLoaderRoute: typeof TradersTraderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/discord-bot': {
      id: '/tools/discord-bot'
      path: '/tools/discord-bot'
      fullPath: '/tools/discord-bot'
      preLoaderRoute: typeof ToolsDiscordBotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quests_/$questId': {
      id: '/quests_/$questId'
      path: '/quests/$questId'
      fullPath: '/quests/$questId'
      preLoaderRoute: typeof QuestsQuestIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maps_/$mapId': {
      id: '/maps_/$mapId'
      path: '/maps/$mapId'
      fullPath: '/maps/$mapId'
      preLoaderRoute: typeof MapsMapIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/items_/recycles': {
      id: '/items_/recycles'
      path: '/items/recycles'
      fullPath: '/items/recycles'
      preLoaderRoute: typeof ItemsRecyclesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/items_/$itemId': {
      id: '/items_/$itemId'
      path: '/items/$itemId'
      fullPath: '/items/$itemId'
      preLoaderRoute: typeof ItemsItemIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hideout_/crafts': {
      id: '/hideout_/crafts'
      path: '/hideout/crafts'
      fullPath: '/hideout/crafts'
      preLoaderRoute: typeof HideoutCraftsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hideout_/$workbenchId': {
      id: '/hideout_/$workbenchId'
      path: '/hideout/$workbenchId'
      fullPath: '/hideout/$workbenchId'
      preLoaderRoute: typeof HideoutWorkbenchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arcs_/$arcId': {
      id: '/arcs_/$arcId'
      path: '/arcs/$arcId'
      fullPath: '/arcs/$arcId'
      preLoaderRoute: typeof ArcsArcIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArcsRoute: ArcsRoute,
  AttributionsRoute: AttributionsRoute,
  HideoutRoute: HideoutRoute,
  ItemsRoute: ItemsRoute,
  MapsRoute: MapsRoute,
  PrivacyRoute: PrivacyRoute,
  QuestsRoute: QuestsRoute,
  TermsRoute: TermsRoute,
  TradersRoute: TradersRoute,
  ArcsArcIdRoute: ArcsArcIdRoute,
  HideoutWorkbenchIdRoute: HideoutWorkbenchIdRoute,
  HideoutCraftsRoute: HideoutCraftsRoute,
  ItemsItemIdRoute: ItemsItemIdRoute,
  ItemsRecyclesRoute: ItemsRecyclesRoute,
  MapsMapIdRoute: MapsMapIdRoute,
  QuestsQuestIdRoute: QuestsQuestIdRoute,
  ToolsDiscordBotRoute: ToolsDiscordBotRoute,
  TradersTraderIdRoute: TradersTraderIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
