/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TraderTraderIdRouteImport } from './routes/trader.$traderId'
import { Route as QuestQuestIdRouteImport } from './routes/quest.$questId'
import { Route as MapMapIdRouteImport } from './routes/map.$mapId'
import { Route as ItemsRecyclesRouteImport } from './routes/items.recycles'
import { Route as ItemItemIdRouteImport } from './routes/item.$itemId'
import { Route as HideoutWorkbenchIdRouteImport } from './routes/hideout.$workbenchId'
import { Route as ArcArcIdRouteImport } from './routes/arc.$arcId'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TraderTraderIdRoute = TraderTraderIdRouteImport.update({
  id: '/trader/$traderId',
  path: '/trader/$traderId',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestQuestIdRoute = QuestQuestIdRouteImport.update({
  id: '/quest/$questId',
  path: '/quest/$questId',
  getParentRoute: () => rootRouteImport,
} as any)
const MapMapIdRoute = MapMapIdRouteImport.update({
  id: '/map/$mapId',
  path: '/map/$mapId',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemsRecyclesRoute = ItemsRecyclesRouteImport.update({
  id: '/items/recycles',
  path: '/items/recycles',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemItemIdRoute = ItemItemIdRouteImport.update({
  id: '/item/$itemId',
  path: '/item/$itemId',
  getParentRoute: () => rootRouteImport,
} as any)
const HideoutWorkbenchIdRoute = HideoutWorkbenchIdRouteImport.update({
  id: '/hideout/$workbenchId',
  path: '/hideout/$workbenchId',
  getParentRoute: () => rootRouteImport,
} as any)
const ArcArcIdRoute = ArcArcIdRouteImport.update({
  id: '/arc/$arcId',
  path: '/arc/$arcId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/arc/$arcId': typeof ArcArcIdRoute
  '/hideout/$workbenchId': typeof HideoutWorkbenchIdRoute
  '/item/$itemId': typeof ItemItemIdRoute
  '/items/recycles': typeof ItemsRecyclesRoute
  '/map/$mapId': typeof MapMapIdRoute
  '/quest/$questId': typeof QuestQuestIdRoute
  '/trader/$traderId': typeof TraderTraderIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/arc/$arcId': typeof ArcArcIdRoute
  '/hideout/$workbenchId': typeof HideoutWorkbenchIdRoute
  '/item/$itemId': typeof ItemItemIdRoute
  '/items/recycles': typeof ItemsRecyclesRoute
  '/map/$mapId': typeof MapMapIdRoute
  '/quest/$questId': typeof QuestQuestIdRoute
  '/trader/$traderId': typeof TraderTraderIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/arc/$arcId': typeof ArcArcIdRoute
  '/hideout/$workbenchId': typeof HideoutWorkbenchIdRoute
  '/item/$itemId': typeof ItemItemIdRoute
  '/items/recycles': typeof ItemsRecyclesRoute
  '/map/$mapId': typeof MapMapIdRoute
  '/quest/$questId': typeof QuestQuestIdRoute
  '/trader/$traderId': typeof TraderTraderIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/privacy'
    | '/terms'
    | '/arc/$arcId'
    | '/hideout/$workbenchId'
    | '/item/$itemId'
    | '/items/recycles'
    | '/map/$mapId'
    | '/quest/$questId'
    | '/trader/$traderId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/privacy'
    | '/terms'
    | '/arc/$arcId'
    | '/hideout/$workbenchId'
    | '/item/$itemId'
    | '/items/recycles'
    | '/map/$mapId'
    | '/quest/$questId'
    | '/trader/$traderId'
  id:
    | '__root__'
    | '/'
    | '/privacy'
    | '/terms'
    | '/arc/$arcId'
    | '/hideout/$workbenchId'
    | '/item/$itemId'
    | '/items/recycles'
    | '/map/$mapId'
    | '/quest/$questId'
    | '/trader/$traderId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  ArcArcIdRoute: typeof ArcArcIdRoute
  HideoutWorkbenchIdRoute: typeof HideoutWorkbenchIdRoute
  ItemItemIdRoute: typeof ItemItemIdRoute
  ItemsRecyclesRoute: typeof ItemsRecyclesRoute
  MapMapIdRoute: typeof MapMapIdRoute
  QuestQuestIdRoute: typeof QuestQuestIdRoute
  TraderTraderIdRoute: typeof TraderTraderIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trader/$traderId': {
      id: '/trader/$traderId'
      path: '/trader/$traderId'
      fullPath: '/trader/$traderId'
      preLoaderRoute: typeof TraderTraderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quest/$questId': {
      id: '/quest/$questId'
      path: '/quest/$questId'
      fullPath: '/quest/$questId'
      preLoaderRoute: typeof QuestQuestIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map/$mapId': {
      id: '/map/$mapId'
      path: '/map/$mapId'
      fullPath: '/map/$mapId'
      preLoaderRoute: typeof MapMapIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/items/recycles': {
      id: '/items/recycles'
      path: '/items/recycles'
      fullPath: '/items/recycles'
      preLoaderRoute: typeof ItemsRecyclesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/item/$itemId': {
      id: '/item/$itemId'
      path: '/item/$itemId'
      fullPath: '/item/$itemId'
      preLoaderRoute: typeof ItemItemIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hideout/$workbenchId': {
      id: '/hideout/$workbenchId'
      path: '/hideout/$workbenchId'
      fullPath: '/hideout/$workbenchId'
      preLoaderRoute: typeof HideoutWorkbenchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arc/$arcId': {
      id: '/arc/$arcId'
      path: '/arc/$arcId'
      fullPath: '/arc/$arcId'
      preLoaderRoute: typeof ArcArcIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  ArcArcIdRoute: ArcArcIdRoute,
  HideoutWorkbenchIdRoute: HideoutWorkbenchIdRoute,
  ItemItemIdRoute: ItemItemIdRoute,
  ItemsRecyclesRoute: ItemsRecyclesRoute,
  MapMapIdRoute: MapMapIdRoute,
  QuestQuestIdRoute: QuestQuestIdRoute,
  TraderTraderIdRoute: TraderTraderIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
